/// Flutter icons ENGRAM
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:

///
///
///
import 'package:flutter/widgets.dart';

class ENGRAM {
  ENGRAM._();

  static const _kFontFam = 'ENGRAM';
  static const _kFontPkg = null;

  static const IconData about =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_image =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
